# Generated by Django 4.0.5 on 2022-06-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlyrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongLyricsWithParametersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songtitle', models.CharField(max_length=5000)),
                ('artist', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='SongLyrics',
        ),
    ]
