# Generated by Django 4.0.5 on 2022-06-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getlyrics', '0002_songlyricswithparametersmodel_delete_songlyrics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongLyricsWithParametersModel',
        ),
    ]
