# Generated by Django 4.0.5 on 2022-06-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getlyrics', '0003_delete_songlyricswithparametersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlyricstest',
            name='song_artist',
            field=models.CharField(default=0, max_length=5000),
        ),
        migrations.AddField(
            model_name='songlyricstest',
            name='song_title',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
