# Generated by Django 4.0.4 on 2022-04-21 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scores', '0002_alter_score_daily_correct_in_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='daily_correct_in_2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='daily_correct_in_3',
        ),
        migrations.RemoveField(
            model_name='score',
            name='daily_correct_in_4',
        ),
        migrations.RemoveField(
            model_name='score',
            name='daily_correct_in_5',
        ),
        migrations.AlterField(
            model_name='score',
            name='daily_correct_in_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_daily_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
