# Generated by Django 4.0.4 on 2022-04-21 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailysongs', '0003_remove_song_song_clue_5_song_daily_song_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0007_remove_league_code_alter_league_league_name'),
        ('scores', '0005_score_daily_correct_in_3_score_daily_correct_in_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='daily_song_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song1_daily_scores', to='dailysongs.song'),
        ),
        migrations.AddField(
            model_name='score',
            name='league_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song1_daily_scores', to='leagues.league'),
        ),
        migrations.AlterField(
            model_name='score',
            name='daily_correct_in_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song1_daily_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='daily_correct_in_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song2_daily_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='daily_correct_in_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song3_daily_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='daily_correct_in_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song4_daily_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='daily_correct_in_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song5_daily_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
