# Generated by Django 4.0.4 on 2022-04-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_score_daily_song_id_score_league_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='daily_song_id',
            new_name='daily_song',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='league_id',
            new_name='league',
        ),
    ]
