# Generated by Django 4.0.4 on 2022-04-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_rename_daily_song_id_score_daily_song_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='daily_correct_in_1',
        ),
    ]
