# Generated by Django 4.0.4 on 2022-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_league_league_users'),
        ('jwt_auth', '0004_alter_customuser_user_leagues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_leagues',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_leagues',
            field=models.ManyToManyField(null=True, related_name='users_league', to='leagues.league'),
        ),
    ]
