# Generated by Django 4.0.4 on 2022-04-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_league_league_users'),
        ('jwt_auth', '0007_remove_customuser_user_leagues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_leagues',
            field=models.ManyToManyField(default=None, related_name='UserLeagues', to='leagues.league'),
        ),
    ]
