# Generated by Django 4.0.4 on 2022-04-21 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_score_daily_correct_in_1_and_more'),
        ('jwt_auth', '0008_customuser_user_leagues'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_song_stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_daily_score_on_song', to='scores.score'),
        ),
    ]
