# Generated by Django 4.0.4 on 2022-04-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0009_customuser_daily_song_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.CharField(choices=[('🐶', 'DOG'), ('🐱', 'CAT'), ('🐭', 'MOUSE'), ('🐰', 'BUNNY'), ('🦊', 'FOX'), ('🐻', 'BEAR'), ('🐼', 'PANDA'), ('🐨', 'KOALA'), ('🐯', 'LION'), ('🐮', 'COW'), ('🐷', 'PIG'), ('🐸', 'FROG'), ('🐵', 'MONKEY'), ('🐥', 'CHICK'), ('🦉', 'OWL'), ('🦄', 'UNICORN')], max_length=10),
        ),
    ]
