# Generated by Django 4.0.4 on 2022-04-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_rename_daily_song_id_score_daily_song_and_more'),
        ('jwt_auth', '0010_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='daily_song_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_daily_score_on_song', to='scores.score'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_avg',
            field=models.FloatField(default='0'),
        ),
    ]
