# Generated by Django 4.0.4 on 2022-04-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0012_alter_customuser_correct_in_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='correct_in_1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='correct_in_2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='correct_in_3',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='correct_in_4',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='correct_in_5',
            field=models.IntegerField(default='0'),
        ),
    ]
