# Generated by Django 4.0.4 on 2022-04-22 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_rename_daily_song_id_score_daily_song_and_more'),
        ('jwt_auth', '0014_alter_customuser_user_leagues'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_correct_in_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_score_in_1', to='scores.score'),
        ),
    ]
