# Generated by Django 4.0.4 on 2022-04-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_remove_score_daily_correct_in_1'),
        ('jwt_auth', '0015_customuser_daily_correct_in_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='daily_correct_in_1',
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_correct_in_1',
            field=models.ManyToManyField(default=None, related_name='daily_correct_in_1', to='scores.score'),
        ),
    ]
