# Generated by Django 4.0.4 on 2022-04-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0016_remove_customuser_daily_correct_in_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='daily_correct_in_1',
        ),
    ]
