# Generated by Django 4.0.4 on 2022-04-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_remove_league_league_users'),
        ('jwt_auth', '0017_remove_customuser_daily_correct_in_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_leagues_names',
            field=models.ManyToManyField(default=None, related_name='league_users_titles', to='leagues.league'),
        ),
    ]
