# Generated by Django 4.0.4 on 2022-04-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0018_customuser_user_leagues_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_leagues_names',
        ),
    ]
