# Generated by Django 4.0.4 on 2022-04-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(max_length=100)),
                ('league_name', models.CharField(max_length=50)),
            ],
        ),
    ]
