# Generated by Django 4.0.4 on 2022-04-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailysongs', '0002_alter_song_song_clue_1_alter_song_song_clue_2_and_more'),
        ('leagues', '0003_league_daily_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='daily_songs',
            field=models.ManyToManyField(default=None, related_name='LeaguesDailySong', to='dailysongs.song'),
        ),
    ]
