# Generated by Django 4.0.4 on 2022-04-20 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0004_alter_league_daily_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_users',
            field=models.ManyToManyField(default=None, related_name='UserLeagues', to=settings.AUTH_USER_MODEL),
        ),
    ]
