# Generated by Django 4.0.4 on 2022-04-20 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_league_league_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
