# Generated by Django 4.0.4 on 2022-04-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_remove_league_code_alter_league_league_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='league_users',
        ),
    ]
