# Generated by Django 4.0 on 2022-04-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50)),
                ('song_clue_1', models.CharField(max_length=150)),
                ('song_clue_2', models.CharField(max_length=150)),
                ('song_clue_3', models.CharField(max_length=150)),
                ('song_clue_4', models.CharField(max_length=150)),
                ('song_clue_5', models.CharField(max_length=150)),
            ],
        ),
    ]
