# Generated by Django 4.0 on 2022-04-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailysongs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_clue_1',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_clue_2',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_clue_3',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_clue_4',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_clue_5',
            field=models.CharField(max_length=300),
        ),
    ]
